services:
  # nginx
  web:
    image: jasonjrz/nginx-php:1.0
    ports:
      - "3000:80"
  # php
  app:
    image: jasonjrz/php-composer:1.1
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
  # mysql
  database:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
  # redis
  cache:
    image: redis:latest

volumes:
  mysqldata: